-- Migration 003 is now a no-op: entry_rationale and exit_rationale columns
-- are included in the initial schema (001_initial.sql) for SQLite.
-- This file exists only to keep the migration tracker consistent.
